/**
 * `tw-file-upload` — selects one or more files via button / click / drag-and-drop.
 *
 * Surfaces the selected files as a `File[]` value through `ControlValueAccessor`
 * so the component works identically with template-driven `ngModel`, reactive
 * `[formControl]`, and signal-based `[formField]` strategies. Integrates with
 * `<tw-form-field>` for label / hint / error chrome.
 *
 * Built-in validation (`accept`, `maxSize`, `maxFiles`) rejects files at the
 * UI layer and surfaces them via the `fileRejected` output and `LiveAnnouncer`.
 * These rejections do NOT flow through `NgControl.errors`, so they cannot be
 * matched with `[twError match="size"]`. Use Angular `Validator`s on the bound
 * `NgControl` for error-key-driven UI (cross-field or async validation).
 *
 * The component does NOT issue HTTP requests. Consumers own the upload pipeline
 * and push progress / status back into the component via `setItemProgress` and
 * `setItemStatus`.
 */
import {
  afterNextRender,
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  contentChild,
  DestroyRef,
  Directive,
  ElementRef,
  forwardRef,
  inject,
  Injector,
  input,
  isDevMode,
  type OnInit,
  output,
  signal,
  type Signal,
  TemplateRef,
  viewChild,
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { type ControlValueAccessor, NgControl } from '@angular/forms';
import { FocusMonitor, LiveAnnouncer } from '@angular/cdk/a11y';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { isObservable } from 'rxjs';
import { tv } from 'tailwind-variants';
import {
  type ErrorStateMatcher,
  type TwSize,
  wireErrorState,
} from '@cdevhub/ngx-tw/core';
import { FormFieldControl, TW_FORM_FIELD_CONTROL } from '@cdevhub/ngx-tw/form-field';
import { ButtonDirective } from '@cdevhub/ngx-tw/button';
import { IconComponent } from '@cdevhub/ngx-tw/icon';
import { ProgressBarComponent } from '@cdevhub/ngx-tw/progress-bar';

/** Lifecycle status of a single selected file. */
export type FileUploadStatus = 'pending' | 'uploading' | 'success' | 'error';

/** Visual variant of the drop zone container. */
export type FileUploadVariant = 'outline' | 'soft';

/** Reason a file was rejected during validation. */
export type FileUploadRejectionReason = 'accept' | 'size' | 'count';

/** A single tracked entry in the file-upload's internal state. */
export interface FileUploadItem {
  /** Stable opaque id for this entry. Generated by the component on add. Use as the key when calling `setItemProgress` / `setItemStatus`. */
  readonly id: string;
  /** The underlying `File` object as provided by the browser (or by `writeValue`). */
  readonly file: File;
  /** Current upload progress, integer 0–100. `0` when no progress has been reported. */
  readonly progress: number;
  /** Current lifecycle status. Defaults to `'pending'`. */
  readonly status: FileUploadStatus;
  /** Optional error message attached when `status === 'error'`. Displayed in the file row and announced via `LiveAnnouncer`. */
  readonly error?: string;
}

/** Payload emitted on `fileRejected`. */
export interface FileUploadRejection {
  /** The browser-supplied `File` that was rejected. */
  readonly file: File;
  /** Why the file was rejected. */
  readonly reason: FileUploadRejectionReason;
  /** Human-readable message suitable for assistive-tech announcement and inline display. */
  readonly message: string;
}

// ── Structural slot directive ────────────────────────────────────

/**
 * Structural directive that captures a template used to render each item row.
 * Apply with `*twFileUploadItem="let item"` to override the default row layout.
 *
 * The template context exposes the current `FileUploadItem` as both `$implicit`
 * and `item`, so both `let-item` and `let-item="item"` work.
 */
@Directive({ selector: 'ng-template[twFileUploadItem]' })
export class FileUploadItemDirective {
  /** @internal Reference to the captured template — read by the host component. */
  readonly templateRef = inject<TemplateRef<{ $implicit: FileUploadItem; item: FileUploadItem }>>(
    TemplateRef,
  );
}

// ── tv() config ──────────────────────────────────────────────────

const fileUploadVariants = tv(
  {
    slots: {
      // `relative` scopes the hidden `<input type="file" class="sr-only">` —
      // its `position: absolute` + `margin: -1px` would otherwise resolve
      // against the nearest positioned ancestor (often `<body>`), extending
      // the document and producing runaway horizontal/vertical scroll.
      root: 'relative flex flex-col gap-3 w-full',
      // 2px dashed border on the outline variant is the dropzone's defining
      // affordance — codified deviation from CLAUDE.md's "2px = active state
      // indicator only" rule. The empty dropzone IS an awaiting-input affordance.
      dropzone:
        'relative rounded-lg transition-[border-color,background-color,transform] duration-200 motion-reduce:transition-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-500 cursor-pointer',
      dropzoneInner: 'flex flex-col items-center justify-center text-center gap-3',
      illustration: 'text-fg-subtle shrink-0',
      headline: 'font-semibold text-fg empty:hidden',
      description: 'text-fg-muted empty:hidden',
      list: 'flex flex-col gap-1 m-0 p-0 list-none empty:hidden',
      item: 'flex items-start gap-3 px-3 py-2 rounded-md hover:bg-surface-muted transition-colors duration-200 motion-reduce:transition-none',
      itemIcon: 'shrink-0 text-fg-muted mt-0.5',
      itemBody: 'flex-1 min-w-0 flex flex-col gap-1',
      itemName: 'text-sm font-medium text-fg truncate',
      itemMeta: 'text-xs text-fg-muted',
      itemProgress: 'mt-1',
      itemActions: 'flex items-center gap-1 shrink-0',
    },
    variants: {
      variant: {
        outline: { dropzone: 'border-2 border-dashed border-border bg-transparent' },
        soft: { dropzone: 'border border-border bg-surface-muted' },
      },
      size: {
        xs: { dropzone: 'p-2', headline: 'text-xs', description: 'text-2xs' },
        sm: { dropzone: 'p-3', headline: 'text-sm', description: 'text-xs' },
        md: { dropzone: 'p-4', headline: 'text-sm', description: 'text-xs' },
        lg: { dropzone: 'p-6', headline: 'text-sm', description: 'text-xs' },
        xl: { dropzone: 'p-8', headline: 'text-sm', description: 'text-xs' },
      },
      state: {
        idle: {},
        // 1% scale-up — below Tailwind's smallest `scale-95` step but visually
        // correct for a subtle drag-over lift; the alternative is no lift.
        // No `dark:` variant here, deliberately. The theme layer already
        // inverts the ramp: `_dark.css` maps `--color-primary-50` onto
        // `blue-950`, so `bg-primary-soft` IS the dark wash in dark mode. A
        // `dark:bg-primary-900/20` override on top resolved to `blue-100` —
        // near-white — and turned the drag-over affordance into a bright flash
        // over a `gray-950` dropzone. These were the only two `dark:` utilities
        // in the library, and both were wrong for this reason.
        draggingValid: {
          dropzone: 'border-primary-500 bg-primary-soft scale-[1.01]',
        },
        draggingInvalid: {
          dropzone: 'border-error-500 bg-error-soft',
        },
        error: { dropzone: 'border-error-500' },
      },
      disabled: {
        true: { dropzone: 'opacity-50 pointer-events-none cursor-not-allowed' },
        false: {},
      },
    },
    defaultVariants: {
      variant: 'outline',
      size: 'md',
      state: 'idle',
      disabled: false,
    },
  },
  { twMerge: true },
);

// ── Module-level counters & helpers ─────────────────────────────

let nextHostId = 0;
let nextItemSeq = 0;

const BYTE_UNITS = ['B', 'KB', 'MB', 'GB', 'TB'] as const;

function formatBytes(n: number): string {
  if (!Number.isFinite(n) || n < 0) return '0 B';
  if (n < 1024) return `${n} B`;
  let v = n;
  let i = 0;
  while (v >= 1024 && i < BYTE_UNITS.length - 1) {
    v /= 1024;
    i += 1;
  }
  return `${v < 10 ? v.toFixed(1) : Math.round(v)} ${BYTE_UNITS[i]}`;
}

function parseAcceptList(accept: string | undefined): string[] {
  if (!accept) return [];
  return accept
    .split(',')
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean);
}

function matchesAccept(file: File, patterns: readonly string[]): boolean {
  if (patterns.length === 0) return true;
  const type = file.type.toLowerCase();
  const name = file.name.toLowerCase();
  for (const pattern of patterns) {
    if (pattern.startsWith('.')) {
      if (name.endsWith(pattern)) return true;
    } else if (pattern.endsWith('/*')) {
      const prefix = pattern.slice(0, -1);
      if (type.startsWith(prefix)) return true;
    } else if (type === pattern) {
      return true;
    }
  }
  return false;
}

function iconNameFor(file: File): string {
  const type = file.type.toLowerCase();
  if (type.startsWith('image/')) return 'image';
  if (type === 'application/pdf') return 'file-text';
  if (type.startsWith('text/')) return 'file-text';
  return 'file';
}

function clampPercent(n: number): number {
  if (!Number.isFinite(n)) return 0;
  if (n < 0) return 0;
  if (n > 100) return 100;
  return Math.round(n);
}

// ── FileUploadComponent ─────────────────────────────────────────

@Component({
  selector: 'tw-file-upload',
  exportAs: 'twFileUpload',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet, ButtonDirective, IconComponent, ProgressBarComponent],
  providers: [
    {
      provide: TW_FORM_FIELD_CONTROL,
      useExisting: forwardRef(() => FileUploadComponent),
    },
  ],
  templateUrl: './file-upload.html',
  host: {
    'role': 'group',
    '[id]': 'id()',
    '[class]': 'rootClasses()',
    '[attr.aria-label]': 'ariaLabel() || null',
    '[attr.aria-labelledby]': 'effectiveAriaLabelledby() || null',
    '[attr.aria-describedby]': 'effectiveAriaDescribedby() || null',
    '[attr.aria-disabled]': 'disabled() || null',
    // NOTE: `aria-required` and `aria-invalid` are NOT set here. ARIA 1.2 does
    // not allow either on `role="group"`, and axe flags it as a *critical*
    // `aria-allowed-attr` violation. Both belong on the control that carries
    // the value: the hidden `<input type="file">` takes native `required` and
    // `aria-invalid` in `file-upload.html`.
  },
})
export class FileUploadComponent
  extends FormFieldControl<File[]>
  implements ControlValueAccessor, OnInit
{
  // ── Inputs ──

  /** When true, the user can select more than one file. Mirrors to the hidden `<input multiple>` attribute. Defaults to `false`. */
  readonly multiple = input<boolean, unknown>(false, { transform: booleanAttribute });

  /** Comma-separated list of accepted file types using the native `<input accept>` syntax (e.g., `'image/*,.pdf'`). Forwarded to the hidden input and used to reject dropped files that do not match. Defaults to `undefined` (accept any). */
  readonly accept = input<string | undefined>(undefined);

  /** Maximum size per file, in bytes. Files exceeding this are rejected with reason `'size'` and never reach `value`. Defaults to `undefined` (no limit). */
  readonly maxSize = input<number | undefined>(undefined);

  /** Maximum total file count. Drops that would push the count over this limit are rejected with reason `'count'`. Ignored when `multiple` is `false` (the limit is always 1). Defaults to `undefined` (no limit). */
  readonly maxFiles = input<number | undefined>(undefined);

  /** Visual style of the drop zone. `'outline'` renders a dashed-bordered transparent region; `'soft'` renders a filled muted background. Defaults to `'outline'`. */
  readonly variant = input<FileUploadVariant>('outline');

  /** Controls overall density: drop-zone padding, icon scale, headline typography. Defaults to `'md'`. */
  readonly size = input<TwSize>('md');

  /** When true, blocks file selection (button, click, drop, keyboard) and applies muted styling. Reactive forms also propagate `disabled` via `setDisabledState`. Defaults to `false`. */
  readonly disabledInput = input<boolean, unknown>(false, {
    alias: 'disabled',
    transform: booleanAttribute,
  });

  /** Marks the control as required. Mirrors to `aria-required`. Also inferred from `Validators.required` on a bound `NgControl`. Defaults to `false`. */
  readonly requiredInput = input<boolean, unknown>(false, {
    alias: 'required',
    transform: booleanAttribute,
  });

  /** Headline text rendered inside the drop zone (e.g., `'Drag files here'`). Projected `[twFileUploadHeadline]` content takes precedence over this input. Defaults to `undefined`. */
  readonly label = input<string | undefined>(undefined);

  /** Secondary text rendered under the label (e.g., `'PDF up to 10MB'`). Projected `[twFileUploadDescription]` content takes precedence. Defaults to `undefined`. */
  readonly description = input<string | undefined>(undefined);

  /** Label rendered inside the trigger button. Defaults to `'Choose files'`. Use `'Choose file'` when `multiple` is `false` (consumer responsibility). */
  readonly triggerLabel = input<string>('Choose files');

  /** Accessible name applied to the host when no visible label is projected. Mirrored to `aria-label`. Defaults to `undefined`. */
  readonly ariaLabel = input<string | undefined>(undefined, { alias: 'aria-label' });

  /** ID of an external element that labels the control. Mirrored to `aria-labelledby`. Defaults to `undefined`. */
  readonly ariaLabelledby = input<string | undefined>(undefined, {
    alias: 'aria-labelledby',
  });

  /** ID of an external element that describes the control. Form-field merges its hint/error ids alongside. Defaults to `undefined`. Alias: `aria-describedby`. */
  readonly ariaDescribedby = input<string | undefined>(undefined, {
    alias: 'aria-describedby',
  });

  /** Optional `name` attribute on the hidden `<input type="file">` for native form submissions. */
  readonly name = input<string | undefined>(undefined);

  /** Id on the host element. Auto-generated as `tw-file-upload-N` when not provided. Used by the form-field's `<label for>` attribute. */
  readonly idInput = input<string | undefined>(undefined, { alias: 'id' });

  /** Per-instance override of the {@link ErrorStateMatcher}. When omitted, the component uses the `TW_ERROR_STATE_MATCHER` token's value. */
  readonly errorStateMatcher = input<ErrorStateMatcher | undefined>(undefined);

  // ── Outputs ──

  /** Fires once per add operation with the items that were accepted and appended. Does not fire for rejected files (see `fileRejected`). Does not fire on `writeValue`. */
  readonly filesAdded = output<FileUploadItem[]>();

  /** Fires when a file is removed via the remove button or programmatic `remove()`. Does not fire on `writeValue`. */
  readonly fileRemoved = output<FileUploadItem>();

  /** Fires for each file that failed validation during add. Payload includes a human-readable message suitable for assistive-tech announcement. */
  readonly fileRejected = output<FileUploadRejection>();

  /** Fires when all files are cleared at once via programmatic `clear()`. Does not fire on `writeValue`, even when the new value is empty. */
  readonly cleared = output<void>();

  // ── Injections ──

  private readonly elementRef = inject(ElementRef<HTMLElement>);
  private readonly injector = inject(Injector);
  private readonly focusMonitor = inject(FocusMonitor);
  private readonly liveAnnouncer = inject(LiveAnnouncer);
  private readonly destroyRef = inject(DestroyRef);
  private readonly ngControl = inject(NgControl, { optional: true, self: true });

  // ── Internal mutable state ──

  private readonly itemsSignal = signal<readonly FileUploadItem[]>([]);
  private readonly cvaDisabled = signal(false);
  private readonly isDraggingSignal = signal(false);
  private readonly dragHasInvalidFilesSignal = signal(false);
  private readonly _focused = signal(false);

  /** @internal Shared `errorState` / `required` / `errors` derivation — see `wireErrorState`. */
  private readonly errorWiring = wireErrorState({
    ngControl: () => this.ngControl,
    matcher: () => this.errorStateMatcher(),
    required: () => this.requiredInput(),
    track: [() => this._focused()],
  });
  private readonly describedByIdsSignal = signal<readonly string[]>([]);
  private readonly labelledByIdsSignal = signal<readonly string[]>([]);

  private dragCounter = 0;

  private onChange: (value: File[]) => void = () => {};
  private onTouched: () => void = () => {};

  // ── Template refs ──

  /** @internal Captured custom-item template (from `*twFileUploadItem`). When absent, the default row template renders. */
  readonly itemSlot = contentChild(FileUploadItemDirective);

  /** @internal Dropzone wrapper — used to scope the form-field container-click guard. */
  private readonly dropzoneRef = viewChild<ElementRef<HTMLElement>>('dropzone');

  /** @internal The visible trigger button — the keyboard-operable control that receives focus on container click and after the last item is removed. */
  private readonly triggerRef = viewChild<ElementRef<HTMLButtonElement>>('trigger');

  /** @internal Hidden native input — used as the OS picker trigger. */
  private readonly hiddenInputRef = viewChild<ElementRef<HTMLInputElement>>('hiddenInput');

  // ── Ids ──

  private readonly uid = nextHostId++;
  /** @internal Auto-generated host id used when `[id]` is not supplied. */
  readonly hostId = `tw-file-upload-${this.uid}`;
  /** @internal */
  readonly headlineId = `${this.hostId}-headline`;
  /** @internal */
  readonly descriptionId = `${this.hostId}-description`;
  /** @internal */
  readonly hiddenInputId = `${this.hostId}-input`;

  // ── Public readonly signals ──

  /** Current items with their progress and status. Snapshot of internal state. */
  readonly items: Signal<readonly FileUploadItem[]> = this.itemsSignal.asReadonly();

  /** True while a valid file drag is over the drop zone. */
  readonly isDragging: Signal<boolean> = this.isDraggingSignal.asReadonly();

  /** Convenience alias for `items().length`. Useful for counter hints. */
  readonly valueLength: Signal<number> = computed(() => this.itemsSignal().length);

  // ── FormFieldControl signals ──

  /** @internal */
  readonly id: Signal<string> = computed(() => this.idInput() ?? this.hostId);

  /** @internal */
  readonly value: Signal<File[] | null> = computed(() => {
    const list = this.itemsSignal();
    return list.length ? list.map((i) => i.file) : null;
  });

  /** @internal */
  readonly focused: Signal<boolean> = this._focused.asReadonly();

  /** @internal */
  readonly empty: Signal<boolean> = computed(() => this.itemsSignal().length === 0);

  /** @internal */
  readonly disabled: Signal<boolean> = computed(() => {
    this.errorWiring.rev();
    return this.disabledInput() || this.cvaDisabled() || !!this.ngControl?.disabled;
  });

  /** @internal */
  readonly required: Signal<boolean> = this.errorWiring.required;

  /** @internal */
  readonly errorState: Signal<boolean> = this.errorWiring.errorState;

  /** @internal Validation errors map from the bound `NgControl`. */
  override readonly errors = this.errorWiring.errors;

  /** @internal */
  readonly controlType = 'file-upload';

  /** @internal */
  readonly userAriaDescribedBy: Signal<string | undefined> = computed(() =>
    this.ariaDescribedby(),
  );

  /** @internal */
  override readonly userAriaLabelledby: Signal<string | undefined> = computed(() =>
    this.ariaLabelledby(),
  );

  // ── Effective ARIA ──
  //
  // When wrapped by `<tw-form-field>`, the form-field calls `setDescribedByIds`
  // / `setLabelledByIds` with the FULLY MERGED id list (hint/error/label + the
  // consumer's `aria-*by` ids). In that case the pushed ids alone are the
  // source of truth. When standalone, fall back to the consumer-supplied
  // `aria-*by` input and the internal description id.

  /** @internal */
  readonly effectiveAriaLabelledby = computed(() => {
    const pushed = this.labelledByIdsSignal();
    if (pushed.length) return pushed.join(' ');
    return this.ariaLabelledby() || undefined;
  });

  /** @internal */
  readonly effectiveAriaDescribedby = computed(() => {
    const pushed = this.describedByIdsSignal();
    if (pushed.length) return pushed.join(' ');
    const merged: string[] = [];
    const external = this.ariaDescribedby();
    if (external) {
      for (const id of external.split(/\s+/).filter(Boolean)) merged.push(id);
    }
    if (this.description()) merged.push(this.descriptionId);
    return merged.length ? merged.join(' ') : undefined;
  });

  // ── Variant computeds ──

  private readonly stateVariant = computed<'idle' | 'draggingValid' | 'draggingInvalid' | 'error'>(
    () => {
      if (this.disabled()) return 'idle';
      if (this.isDraggingSignal()) {
        return this.dragHasInvalidFilesSignal() ? 'draggingInvalid' : 'draggingValid';
      }
      if (this.errorState()) return 'error';
      return 'idle';
    },
  );

  private readonly variantResult = computed(() =>
    fileUploadVariants({
      variant: this.variant(),
      size: this.size(),
      state: this.stateVariant(),
      disabled: this.disabled(),
    }),
  );

  /** @internal */
  readonly rootClasses = computed(() => this.variantResult().root());
  /** @internal */
  readonly dropzoneClasses = computed(() => this.variantResult().dropzone());
  /** @internal */
  readonly dropzoneInnerClasses = computed(() => this.variantResult().dropzoneInner());
  /** @internal */
  readonly illustrationClasses = computed(() => this.variantResult().illustration());
  /** @internal */
  readonly headlineClasses = computed(() => this.variantResult().headline());
  /** @internal */
  readonly descriptionClasses = computed(() => this.variantResult().description());
  /** @internal */
  readonly listClasses = computed(() => this.variantResult().list());
  /** @internal */
  readonly itemClasses = computed(() => this.variantResult().item());
  /** @internal */
  readonly itemIconClasses = computed(() => this.variantResult().itemIcon());
  /** @internal */
  readonly itemBodyClasses = computed(() => this.variantResult().itemBody());
  /** @internal */
  readonly itemNameClasses = computed(() => this.variantResult().itemName());
  /** @internal */
  readonly itemMetaClasses = computed(() => this.variantResult().itemMeta());
  /** @internal */
  readonly itemProgressClasses = computed(() => this.variantResult().itemProgress());
  /** @internal */
  readonly itemActionsClasses = computed(() => this.variantResult().itemActions());

  /** @internal Mapping component size → icon size for the illustration. */
  readonly iconSize = computed<TwSize>(() => {
    const s = this.size();
    if (s === 'xs') return 'sm';
    if (s === 'sm') return 'md';
    if (s === 'md') return 'lg';
    return 'xl';
  });

  // ── Construction ──

  constructor() {
    super();
    // Runtime CVA wiring — incompatible with a static NG_VALUE_ACCESSOR provider
    // because `inject(NgControl, { self: true })` for matcher integration would
    // create a circular DI on the same element.
    if (this.ngControl) {
      this.ngControl.valueAccessor = this;
    }

    afterNextRender(() => {
      if (isDevMode() && !this.hasAccessibleNameHint()) {
        console.warn(
          '[tw-file-upload] The file-upload has no accessible name. Provide a `label`, project label content, or set `aria-label` / `aria-labelledby`.',
        );
      }
    });
  }

  // ── Public API ──

  /** Programmatically opens the OS file picker. No-op when disabled. */
  open(): void {
    if (this.disabled()) return;
    const input = this.hiddenInputRef()?.nativeElement;
    if (input) input.click();
  }

  /** Removes the item with the given id. Emits `fileRemoved`. No-op when the id is unknown or the component is disabled. */
  remove(id: string): void {
    if (this.disabled()) return;
    const current = this.itemsSignal();
    const idx = current.findIndex((i) => i.id === id);
    if (idx === -1) return;
    const removed = current[idx];
    const next = current.slice(0, idx).concat(current.slice(idx + 1));
    this.itemsSignal.set(next);
    this.emitChange();
    this.fileRemoved.emit(removed);
    this.liveAnnouncer.announce(`${removed.file.name} removed.`, 'polite');
    // Move focus to the next remove button, or to the trigger button when none
    // remain.
    //
    // This MUST wait for the render, not merely for the microtask queue. A
    // `queueMicrotask` here (what this used to be) runs before Angular's
    // zoneless scheduler has re-rendered the list, so `nextButtons` was still
    // the PRE-removal node list: the "next" button we focused was the one about
    // to be destroyed, and focus fell to `<body>`. Removing the last item took
    // the `length === 0` branch for the same reason — the count was stale, so
    // the trigger never got focus either.
    //
    // It survived unit testing because a spec that calls `detectChanges()`
    // between the click and the assertion has already re-rendered by the time
    // the microtask runs, which is the opposite order from a real browser.
    afterNextRender(
      () => {
        const host = this.elementRef.nativeElement as HTMLElement;
        const nextButtons = host.querySelectorAll('[data-tw-file-upload-remove]');
        if (nextButtons.length === 0) {
          this.triggerRef()?.nativeElement.focus();
        } else {
          const fallback = nextButtons[Math.min(idx, nextButtons.length - 1)] as
            | HTMLButtonElement
            | undefined;
          fallback?.focus();
        }
      },
      { injector: this.injector },
    );
  }

  /** Removes all items. Emits `cleared` and calls `onChange([])`. No-op when already empty or disabled. */
  clear(): void {
    if (this.disabled()) return;
    if (this.itemsSignal().length === 0) return;
    this.itemsSignal.set([]);
    this.emitChange();
    this.cleared.emit();
    this.liveAnnouncer.announce('All files removed.', 'polite');
  }

  /** Updates the per-item progress (0–100, clamped). Does not change status. No-op when the id is unknown. */
  setItemProgress(id: string, percent: number): void {
    const clamped = clampPercent(percent);
    let found = false;
    const next = this.itemsSignal().map((item) => {
      if (item.id !== id) return item;
      found = true;
      if (item.progress === clamped) return item;
      return { ...item, progress: clamped };
    });
    if (found) this.itemsSignal.set(next);
  }

  /** Updates the per-item status and (optionally) the error message. Announces status transitions via `LiveAnnouncer`. No-op when the id is unknown. */
  setItemStatus(id: string, status: FileUploadStatus, error?: string): void {
    let target: FileUploadItem | undefined;
    let changed = false;
    const next = this.itemsSignal().map((item) => {
      if (item.id !== id) return item;
      target = item;
      const nextError = error !== undefined ? error : item.error;
      if (item.status === status && item.error === nextError) return item;
      changed = true;
      return { ...item, status, error: nextError };
    });
    if (!target) return;
    if (changed) this.itemsSignal.set(next);
    const name = target.file.name;
    if (status === 'success') {
      this.liveAnnouncer.announce(`${name} upload complete.`, 'polite');
    } else if (status === 'error') {
      this.liveAnnouncer.announce(
        error ? `${name} upload failed: ${error}.` : `${name} upload failed.`,
        'polite',
      );
    } else if (status === 'uploading') {
      this.liveAnnouncer.announce(`${name} uploading.`, 'polite');
    }
  }

  // ── Drag-drop handlers ──

  /** @internal */
  onDragEnter(event: DragEvent): void {
    if (this.disabled()) return;
    if (!this.isFileDrag(event)) return;
    event.preventDefault();
    this.dragCounter += 1;
    if (this.dragCounter === 1) {
      this.dragHasInvalidFilesSignal.set(this.computeDragInvalid(event));
      this.isDraggingSignal.set(true);
    }
  }

  /** @internal */
  onDragOver(event: DragEvent): void {
    if (this.disabled()) return;
    if (!this.isFileDrag(event)) return;
    // Required to enable `drop` — browsers reject drops by default.
    event.preventDefault();
  }

  /** @internal */
  onDragLeave(event: DragEvent): void {
    if (this.disabled()) return;
    if (!this.isFileDrag(event)) return;
    if (this.dragCounter > 0) this.dragCounter -= 1;
    if (this.dragCounter === 0) {
      this.isDraggingSignal.set(false);
      this.dragHasInvalidFilesSignal.set(false);
    }
  }

  /** @internal */
  onDrop(event: DragEvent): void {
    if (this.disabled()) return;
    event.preventDefault();
    this.dragCounter = 0;
    this.isDraggingSignal.set(false);
    this.dragHasInvalidFilesSignal.set(false);
    const files = event.dataTransfer?.files;
    if (files && files.length) {
      this.addFiles(files);
    }
  }

  /** @internal */
  onTriggerClick(event: MouseEvent): void {
    event.stopPropagation();
    this.open();
  }

  /** @internal Called by the hidden `<input type="file">` `change` event. */
  onNativeChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    const files = target.files;
    if (files && files.length) this.addFiles(files);
    // Reset so re-selecting the same file re-fires `change`.
    target.value = '';
  }

  // ── Add files (validation + commit) ──

  private addFiles(files: FileList | readonly File[]): void {
    if (this.disabled()) return;
    const incoming: File[] = Array.from(files);
    if (incoming.length === 0) return;

    // Single-file mode: replace existing entry with the latest file dropped/selected.
    if (!this.multiple()) {
      const file = incoming[0];
      if (!file) return;
      const patterns = parseAcceptList(this.accept());
      if (!matchesAccept(file, patterns)) {
        this.reject(file, 'accept');
        return;
      }
      const maxSize = this.maxSize();
      if (maxSize !== undefined && file.size > maxSize) {
        this.reject(file, 'size');
        return;
      }
      const newItem = this.wrapFile(file);
      this.itemsSignal.set([newItem]);
      this.emitChange();
      this.filesAdded.emit([newItem]);
      this.liveAnnouncer.announce('1 file added.', 'polite');
      return;
    }

    const patterns = parseAcceptList(this.accept());
    const maxSize = this.maxSize();
    const maxFiles = this.maxFiles();
    const accepted: FileUploadItem[] = [];
    const currentCount = this.itemsSignal().length;

    for (const file of incoming) {
      if (!matchesAccept(file, patterns)) {
        this.reject(file, 'accept');
        continue;
      }
      if (maxSize !== undefined && file.size > maxSize) {
        this.reject(file, 'size');
        continue;
      }
      if (maxFiles !== undefined && currentCount + accepted.length >= maxFiles) {
        this.reject(file, 'count');
        continue;
      }
      accepted.push(this.wrapFile(file));
    }

    if (accepted.length === 0) return;

    this.itemsSignal.set([...this.itemsSignal(), ...accepted]);
    this.emitChange();
    this.filesAdded.emit(accepted);
    this.liveAnnouncer.announce(
      `${accepted.length} file${accepted.length === 1 ? '' : 's'} added.`,
      'polite',
    );
  }

  private wrapFile(file: File): FileUploadItem {
    return {
      id: `tw-file-upload-item-${nextItemSeq++}`,
      file,
      progress: 0,
      status: 'pending',
    };
  }

  private reject(file: File, reason: FileUploadRejectionReason): void {
    const message = this.rejectionMessage(file, reason);
    // Sequence per-file announcements so a batch of rejections is announced cleanly.
    setTimeout(() => this.liveAnnouncer.announce(message, 'polite'));
    this.fileRejected.emit({ file, reason, message });
  }

  private rejectionMessage(file: File, reason: FileUploadRejectionReason): string {
    if (reason === 'accept') return `${file.name} was rejected: file type not allowed.`;
    if (reason === 'size') {
      const max = this.maxSize();
      const limit = max !== undefined ? formatBytes(max) : 'allowed size';
      return `${file.name} was rejected: exceeds ${limit}.`;
    }
    return `${file.name} was rejected: maximum file count reached.`;
  }

  // ── Drag inspection ──

  private isFileDrag(event: DragEvent): boolean {
    const dt = event.dataTransfer;
    if (!dt) return false;
    // `types` includes 'Files' when files are being dragged from the OS.
    return Array.from(dt.types).includes('Files');
  }

  private computeDragInvalid(event: DragEvent): boolean {
    const patterns = parseAcceptList(this.accept());
    if (patterns.length === 0) return false;
    const items = event.dataTransfer?.items;
    if (!items || items.length === 0) return false;
    // During drag, filenames are not exposed — only MIME types via `items[i].type`.
    // Extension-only patterns (`.pdf`) can't be confirmed mid-drag, so we treat
    // the drag as potentially valid if ANY item could match by MIME or if the
    // accept list contains any extension-only pattern.
    const hasExtensionPattern = patterns.some((p) => p.startsWith('.'));
    if (hasExtensionPattern) return false;
    for (const item of Array.from(items)) {
      if (item.kind !== 'file') continue;
      const type = item.type.toLowerCase();
      for (const pattern of patterns) {
        if (pattern.endsWith('/*')) {
          if (type.startsWith(pattern.slice(0, -1))) return false;
        } else if (type === pattern) {
          return false;
        }
      }
    }
    return true;
  }

  // ── ControlValueAccessor ──

  writeValue(value: File[] | File | null | undefined): void {
    if (value === null || value === undefined) {
      if (this.itemsSignal().length === 0) return;
      this.itemsSignal.set([]);
      return;
    }
    const list: File[] = Array.isArray(value) ? value : [value];
    if (list.length === 0) {
      if (this.itemsSignal().length === 0) return;
      this.itemsSignal.set([]);
      return;
    }
    const current = this.itemsSignal();
    if (
      current.length === list.length &&
      current.every((item, idx) => item.file === list[idx])
    ) {
      return;
    }
    this.itemsSignal.set(list.map((file) => this.wrapFile(file)));
  }

  registerOnChange(fn: (value: File[]) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.cvaDisabled.set(isDisabled);
  }

  private emitChange(): void {
    const files = this.itemsSignal().map((i) => i.file);
    this.onChange(files);
  }

  // ── FormFieldControl methods ──

  /** @internal */
  setDescribedByIds(ids: string[]): void {
    this.describedByIdsSignal.set([...ids]);
  }

  /** @internal */
  override setLabelledByIds(ids: string[]): void {
    this.labelledByIdsSignal.set([...ids]);
  }

  /** @internal */
  onContainerClick(event: MouseEvent): void {
    if (this.disabled()) return;
    if (event.defaultPrevented) return;
    const dropzone = this.dropzoneRef()?.nativeElement;
    if (!dropzone) return;
    const target = event.target as Node | null;
    if (target && dropzone.contains(target)) return;
    this.triggerRef()?.nativeElement.focus();
  }

  // ── Rendering helpers ──

  /** @internal */
  iconNameFor(item: FileUploadItem): string {
    return iconNameFor(item.file);
  }

  /** @internal */
  shouldShowProgress(item: FileUploadItem): boolean {
    if (item.status === 'pending' && item.progress === 0) return false;
    return true;
  }

  /** @internal */
  progressColorFor(item: FileUploadItem): 'primary' | 'success' | 'error' {
    if (item.status === 'error') return 'error';
    if (item.status === 'success' || item.progress >= 100) return 'success';
    return 'primary';
  }

  /** @internal */
  metaTextFor(item: FileUploadItem): string {
    const size = formatBytes(item.file.size);
    if (item.status === 'pending') return size;
    if (item.status === 'uploading') return `${size} · Uploading`;
    if (item.status === 'success') return `${size} · Done`;
    if (item.error) return `${size} · Failed — ${item.error}`;
    return `${size} · Failed`;
  }

  // ── Lifecycle ──

  ngOnInit(): void {
    const monitor$ = this.focusMonitor.monitor(this.elementRef, true);
    if (isObservable(monitor$)) {
      monitor$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe((origin) => {
        const wasFocused = this._focused();
        this._focused.set(!!origin);
        if (wasFocused && !origin) {
          this.onTouched();
          this.errorWiring.bump();
        }
      });
    }
    this.destroyRef.onDestroy(() => {
      this.focusMonitor.stopMonitoring(this.elementRef);
    });

    this.errorWiring.connect();
  }

  // ── Helpers ──

  private hasAccessibleNameHint(): boolean {
    if (this.label() || this.ariaLabel() || this.ariaLabelledby()) return true;
    const host = this.elementRef.nativeElement;
    return !!host.textContent && host.textContent.trim().length > 0;
  }
}
